image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.ap-southeast-2.amazonaws.com/myapp
  tag: "0.1.0"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}