apiVersion: v2
name: kube-prometheus-stack        # wrapper name (can keep as-is)
description: Wrapper chart to install kube-prometheus-stack via Argo CD
type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: 62.8.0   # check latest
    repository: https://prometheus-community.github.io/helm-charts
    alias: kps