kps:
  grafana:
    enabled: true
    adminPassword: admin
    service:
      type: LoadBalancer   # ClusterIP if you don't want an ELB
    persistence:
      enabled: false

  alertmanager:
    enabled: false

  prometheus:
    enabled: true
    service:
      type: LoadBalancer   # ClusterIP if you don't want an ELB
    prometheusSpec:
      retention: 7d
      storageSpec: {}      # ephemeral for dev

  prometheusOperator:
    admissionWebhooks:
      enabled: false
      patch:
        enabled: false