prometheus:
  enabled: true
  prometheusSpec:
    retention: 7d
    storageSpec: {}  # ephemeral ok for dev
alertmanager:
  enabled: false
grafana:
  enabled: true
  adminPassword: admin
  service:
    type: ClusterIP
  persistence:
    enabled: false
prometheusOperator:
  admissionWebhooks:
    patch:
      enabled: false   # avoids the extra patch jobs/RBAC churn in dev