kps:
  grafana:
    enabled: true
    adminPassword: admin
    service:
      type: LoadBalancer          # change to LoadBalancer if you want an ELB
    persistence:
      enabled: false

  alertmanager:
    enabled: false

  prometheus:
    enabled: true
    prometheusSpec:
      retention: 7d
      storageSpec: {}          # ephemeral for dev
    service:
      type: LoadBalancer          # change to LoadBalancer if you want an ELB

  prometheusOperator:
    admissionWebhooks:
      enabled: false           # disable the webhook & its patch job
      patch:
        enabled: false