kps:
  kubeEtcd:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false

  prometheusOperator:
    # Keep webhooks off while bootstrapping if you like; turn on later for validation.
    admissionWebhooks:
      enabled: false
      patch:
        enabled: false

  grafana:
    enabled: true
    adminPassword: admin
    service:
      type: ClusterIP           # or ClusterIP if you’ll port-forward
    persistence:
      enabled: false

  alertmanager:
    enabled: false

  prometheus:
    enabled: true
    service:
      type: ClusterIP           # or ClusterIP for port-forwarding
    prometheusSpec:
      retention: 7d
      storageSpec: {}              # no PVCs for first run
      serviceMonitorSelectorNilUsesHelmValues: false