# NOTE: nest under the alias key
kps:
  grafana:
    enabled: true
    adminPassword: admin
    service: { type: ClusterIP }
    persistence: { enabled: false }

  alertmanager:
    enabled: false

  prometheus:
    enabled: true
    prometheusSpec:
      retention: 7d
      storageSpec: {}

  prometheusOperator:
    admissionWebhooks:
      patch:
        enabled: false