grafana:
  enabled: true
  adminPassword: admin
  service:
    type: ClusterIP
  persistence:
    enabled: false

alertmanager:
  enabled: false

prometheus:
  enabled: true          # <-- add this
  prometheusSpec:
    retention: 7d
    storageSpec: {}      # no PVC yet (ephemeral)