image:
  repository: 685801731369.dkr.ecr.ap-southeast-2.amazonaws.com/students-demo
  tag: "83c7d20" # better: use immutable tag (e.g., Git SHA) and have CI bump this
  pullPolicy: IfNotPresent
replicaCount: 1
service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
resources: {}
