image:
  repository: 685801731369.dkr.ecr.ap-southeast-2.amazonaws.com/myapp
  tag: "0.1.0"          # CI will bump this to the new SHA/tag
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources: {}