image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.ap-southeast-2.amazonaws.com/myapp
  tag: "0.1.0"   # CI in app repo will bump this
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources: {}