apiVersion: v1
kind: Service
metadata:
  name: myapp2
  labels:
    app: myapp2
spec:
  type: {{ .Values.service.type }}
  selector:
    app: myapp2
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}