apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://github.com/jimmy23782/GitOpsRepo.git
    targetRevision: feature/setuphelmcharts   # switch to main later
    path: gitopsRepo/helm-charts/kube-prometheus-stack
    helm:
      version: v3
      releaseName: kube-prometheus-stack-dev
      skipCrds: true
      valueFiles:
        - values-kps-dev.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
      - Replace=true
      - Timeout=600