apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-dev
  namespace: argocd
spec:
  project: default   # or: Jimmys-argocd-project-default
  source:
    repoURL: https://github.com/jimmy23782/GitOpsRepo.git
    targetRevision: feature/setuphelmcharts
    path: helm-charts/myapp                # <-- FIXED (remove gitopsRepo/)
    helm:
      valueFiles:
        - values.yaml
        - ../../gitops/environments/dev/values-myapp-dev.yaml   # <-- FIXED (add gitops/)
      ignoreMissingValueFiles: false
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true