apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-dev
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/jimmy23782/GitOpsRepo.git
    targetRevision: feature/setuphelmcharts
    path: gitopsRepo/helm-charts/myapp
    helm:
      valueFiles:
        - gitops/environments/dev/values-myapp-dev.yaml
      ignoreMissingValueFiles: false
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true